# Generated by Django 5.2.14 on 2026-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес')),
                ('vendor', models.CharField(default='Cisco', max_length=100, verbose_name='Вендор')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Локация')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Коммутатор',
                'verbose_name_plural': 'Коммутаторы',
                'ordering': ['name'],
            },
        ),
    ]
