# Generated by Django 5.2.14 on 2026-06-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_operationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(max_length=100, verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('bulk_delete', 'Массовое удаление'), ('info', 'Вывод информации'), ('backup', 'Создание backup'), ('ports_shutdown', 'Отключение портов'), ('ports_no_shutdown', 'Включение портов')], max_length=30, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='NetworkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('info', 'Вывести информацию'), ('backup', 'Создать backup'), ('ports_shutdown', 'Отключить порты'), ('ports_no_shutdown', 'Включить порты')], max_length=30, verbose_name='Тип операции')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус')),
                ('selected_ports', models.JSONField(blank=True, default=list, verbose_name='Выбранные порты')),
                ('command_preview', models.TextField(blank=True, verbose_name='Команда / playbook')),
                ('stdout', models.TextField(blank=True, verbose_name='Вывод')),
                ('stderr', models.TextField(blank=True, verbose_name='Ошибки')),
                ('backup_file', models.CharField(blank=True, max_length=255, verbose_name='Файл backup')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_tasks', to='devices.device', verbose_name='Коммутатор')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сетевая операция',
                'verbose_name_plural': 'Сетевые операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
