---
- name: Получить информацию
  hosts: switches
  gather_facts: false

  tasks:
    - name: Получить информацию
      cisco.ios.ios_command:
        commands:
          - show version | include Version
          - show version | include uptime
          - show version | include image
          - show version | include Processor.board.ID
          - show ip interface brief
      register: command_result

    - name: Вывести информацию
      ansible.builtin.debug:
        var: command_result.stdout_lines
